// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6wdOSZmRnafJN9vkCbzLeEZ8tzC8_CI',
    appId: '1:998653245790:web:adf904078666e56ae2b7cf',
    messagingSenderId: '998653245790',
    projectId: 'fruit-hup-98bb8',
    authDomain: 'fruit-hup-98bb8.firebaseapp.com',
    storageBucket: 'fruit-hup-98bb8.firebasestorage.app',
    measurementId: 'G-BSHH1PBK6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2DItwVs9NJ43Ie79QB67sUmAlo2zXNDk',
    appId: '1:998653245790:android:d94569a602094424e2b7cf',
    messagingSenderId: '998653245790',
    projectId: 'fruit-hup-98bb8',
    storageBucket: 'fruit-hup-98bb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKwzuX8SBKtsCjYFJ_tgy_VosXHRh-R88',
    appId: '1:998653245790:ios:4aba6113b79b28bae2b7cf',
    messagingSenderId: '998653245790',
    projectId: 'fruit-hup-98bb8',
    storageBucket: 'fruit-hup-98bb8.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKwzuX8SBKtsCjYFJ_tgy_VosXHRh-R88',
    appId: '1:998653245790:ios:4aba6113b79b28bae2b7cf',
    messagingSenderId: '998653245790',
    projectId: 'fruit-hup-98bb8',
    storageBucket: 'fruit-hup-98bb8.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM6wdOSZmRnafJN9vkCbzLeEZ8tzC8_CI',
    appId: '1:998653245790:web:e2f38b5f0a2abef0e2b7cf',
    messagingSenderId: '998653245790',
    projectId: 'fruit-hup-98bb8',
    authDomain: 'fruit-hup-98bb8.firebaseapp.com',
    storageBucket: 'fruit-hup-98bb8.firebasestorage.app',
    measurementId: 'G-K6X9NYMQX8',
  );
}
